# Generated by Django 5.1.1 on 2024-10-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="description",
        ),
        migrations.AddField(
            model_name="photo",
            name="name",
            field=models.TextField(blank=True, unique=True),
        ),
    ]
