# Generated by Django 5.1.1 on 2024-10-05 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixel", "0004_alter_photo_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
