# Generated by Django 5.1.1 on 2024-10-20 12:37

import pixel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixel", "0007_alter_photo_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="upload_folder",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to=pixel.models.upload_to),
        ),
    ]
