# Generated by Django 5.1.1 on 2024-10-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixel", "0008_photo_upload_folder_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="upload_folder",
            field=models.CharField(blank=True, default="./static/all/", max_length=100),
        ),
    ]
